// <auto-generated />
using ExamPractice.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ExamPractice.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180418174715_fet")]
    partial class fet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExamPractice.Models.Planet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DockId");

                    b.Property<string>("Name");

                    b.Property<long>("Population");

                    b.HasKey("Id");

                    b.HasIndex("DockId");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("ExamPractice.Models.Spaceship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MaxCapacity");

                    b.Property<string>("Planet");

                    b.Property<int>("Utilization");

                    b.HasKey("Id");

                    b.ToTable("Spaceships");
                });

            modelBuilder.Entity("ExamPractice.Models.Planet", b =>
                {
                    b.HasOne("ExamPractice.Models.Spaceship", "Dock")
                        .WithMany()
                        .HasForeignKey("DockId");
                });
#pragma warning restore 612, 618
        }
    }
}
